### ISSUE TITLE
Credit original repository

### ISSUE THREAD

**Issue by ianzhao05** [IshaanOhri/Capture#3]
I noticed that you attributed me in your README. Thank you for that. However, I _personally_ did not "help" you with the code, so I think it would be more appropriate to **link the original repository** instead (https://github.com/ianzhao05/textshot). Again, I think something like `Based on [TextShot](https://github.com/ianzhao05/textshot)` in the introductory paragraph in the README would be good. I'm sure you aren't deliberately trying to bury the fact that you took my idea, but it seems like you are right now.

This is an immature exchange that should not have existed in the first place, so this is my last request. I hope you follow my request and end this discussion. If not, I may consider a DMCA complaint because you are taking copyright ownership of my idea and code taken from TextShot.

**Comment by IshaanOhri** [comment]
It's not a copy of your project. I took inspiration and built it from scratch. No code was copied. I gave reference to you and that's all I can. It's not based on your project. Your code wasn't even working. I hope you understand. Thanks.

**Comment by ianzhao05** [comment]
I'm not sure you can argue that "no code was copied." On my previous issue which you deleted for some reason, I outlined a few places where you quite obviously copied my code. My code was working by the way; it worked fine on the majority of systems and had some bugs for others. Even if it "wasn't even working," that is no excuse to copy some portions of it.

Please remove my name from the README because I didn't personally help you and link TextShot instead. If you really don't want others knowing about TextShot and the fact that you borrowed the idea and some code, feel free to leave it buried in the "Inspirational Credits" section. Just include my copyright notice in your license, like `Copyright (c) 2020 Ishaan Ohri, Ian Zhao`. Failing to do so is copyright infringement per the MIT license of TextShot.

I really don't want to argue about this anymore. I worked hard on TextShot, and I hope you be the bigger person and give it the credit it deserves.

**Comment by IshaanOhri** [comment]
I'll be more than happy to include your copyright in the license. And I'll link your project as well. Thanks. And trust me I did not copy. I really just took inspiration and wrote from scratch. I'll be including both the things in a while.

**Comment by ianzhao05** [comment]
Ok, I try to believe you when you say you did not copy, but it's hard to find an explanation for these codes:
```
self.screen = QApplication.screenAt(QCursor.pos()).grabWindow(0)
```
This is a very non-obvious way of taking a screenshot that will support multiple monitors and cannot be found on the Internet. Unless you came up with it yourself, in which case I am mistaken.
```
def mouseMoveEvent(self, session):
    self.end = session.pos()
    self.update()
    return super().mousePressEvent(session)
```
Exact same as my function, just renamed `event` to `session`.
```
# buffer = QBuffer()
# buffer.open(QBuffer.ReadWrite)
# screenShot.save(buffer, "PNG")
# img = Image.open(io.BytesIO(buffer.data()))
# buffer.close()
```
(obviously you didn't use these lines, but it at least shows that you took a look at my code)

Anyway, seems like I'm beating a dead horse here, and including my copyright notice will clear you even if you copied code. Thanks for your PR on my original repository, good day.

**Comment by IshaanOhri** [comment]
First part was on a stackoverflow answer
Second is listed in their documentation and refered YouTube as well.
Third is not there in my code. I was just comparing the performance of my code with yours but I removed it later because it would have been wrong to use it because it was yours.

I really feel this conversation is going nowhere and wish to close it because I have agreed to give inspirational credits to your project and include your copyright.

**Comment by ianzhao05** [comment]
Yes, totally agree, this conversation was a result of immaturity on both of our parts.

**Comment by ianzhao05** [comment]
Hate to make another comment, but you said you would link my project, but you still link my profile. I do not want my name there, because my project inspired you, not me personally.

By the way, I took a look at your version, and I think you did a great job! Your README is very well formatted too.

**Comment by IshaanOhri** [comment]
I'll change that and link your project. No hard feelings bro. Peace ✌️
